- hosts: app
  become: true
  tasks:
  
  - name: install required packages
    apt:
      pkg:
        - curl
        - git
        - lynx
        - python3-pip
      state: latest
      update_cache: true

  - name: install docker SDK for python
    pip:
      name: docker
      state: present
      executable: pip3

  - name: add docker apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add docker repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: update apt and install docker-ce
    apt:
      name: docker-ce
      state: latest
      update_cache: true

  - name: add current user to the docker group (optional)
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes

  - name: clone github repo
    git:
      repo: 'https://github.com/mdn/django-locallibrary-tutorial.git'
      dest: /home/{{ ansible_user }}/app
      version: main
      update: yes

  - name: pull the Django docker image
    docker_image:
      name: timurbabs/django
      tag: latest
      source: pull

  - name: run the django container
    docker_container:
      name: django_app
      image: timurbabs/django:latest
      state: started
      restart_policy: always
      ports:
        - "8000:8000"
