- hosts: app
  become: true
  tasks:
  
  - name: Install required system packages
    apt:
      pkg:
        - curl
        - git
        - lynx
        - python3-pip
      state: latest
      update_cache: true

  - name: Install Docker SDK for Python
    pip:
      name: docker
      state: present
      executable: pip3

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Update apt and install docker-ce
    apt:
      name: docker-ce
      state: latest
      update_cache: true

  - name: Add current user to the docker group (optional)
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes

  - name: Clone github repo
    git:
      repo: 'https://github.com/mdn/django-locallibrary-tutorial.git'
      dest: /home/{{ ansible_user }}/app
      version: main
      update: yes

  - name: Pull the Django Docker image
    docker_image:
      name: timurbabs/django
      tag: latest
      source: pull

  - name: Run the Django container
    docker_container:
      name: django_app
      image: timurbabs/django:latest
      state: started
      restart_policy: always
      ports:
        - "8000:8000"
