---
- hosts: app
  become: yes

  roles:
    - Docker

  tasks:
    - name: pull django docker image
      docker_image:
        name: timurbabs/django
        tag: latest
        source: pull

    - name: run django container
      docker_container:
        name: django_app
        image: timurbabs/django:latest
        state: started
        restart_policy: always
        ports:
          - "8000:8000"
